/* Alzarsi product catalog — update brands and products here. */
window.ALZARSI_CATALOG = {
  /* Change only this block to update the featured brand spread. */
  featuredBrand: {
    brandId: "kikko",
    title: "Una tradición de sabor que llega a nuevas cocinas.",
    text: "Conoce la selección Kikko: salsas de soya y especialidades orientales para dar profundidad, aroma y carácter a cada preparación.",
    image: "assets/catalog/featured-kikko-chaufa.png",
    imageAlt: "Arroz chaufa preparado con productos Kikko",
    color: "#eee978",
  },
  brands: [
    {
      id: "lee-kum-kee",
      name: "Lee Kum Kee",
      logo: "assets/brands/lee-kum-kee.png",
      intro:
        "Salsas y condimentos asiáticos para hogares, restaurantes y cocinas profesionales.",
      story:
        "Una selección versátil para incorporar sabores intensos, marinados y terminaciones a la cocina cotidiana y al canal gastronómico.",
      cities: ["la-paz", "santa-cruz"],
      heroImage:
        "assets/products/lee-kum-kee/salsa-soya-sazonada-para-mariscos-410-ml.png",
      catalogStatus: "available",
      theme: {
        background: "#f4eee2",
        surface: "#f8f3e9",
        text: "#241b17",
        accent: "#b88a35",
        contrast: "#1c0909",
        onContrast: "#fff7e8",
      },
      presentation: {
        heroBanner:
          "assets/brands/lee-kum-kee/familia-sabores-que-unen-es.png",
        heroBannerAlt:
          "Familia compartiendo una comida — Sabores que unen de Lee Kum Kee",
        heroHeadline: "Sabor auténtico para cocinas que exigen más.",
        heroHeadlineLines: [
          "Sabor auténtico",
          "para cocinas",
          "que exigen más.",
        ],
        statement: "Una tradición de sabor. Un portafolio para hoy.",
        statementLines: [
          "Una tradición",
          "de sabor. Un",
          "portafolio para hoy.",
        ],
        heroProducts: [
          "lee-kum-kee-salsa-soya-sazonada-para-mariscos-410-ml",
          "lee-kum-kee-aceite-de-sesamo-pure-sesame-oil-270-ml",
          "lee-kum-kee-salsa-con-sabor-a-ostion-marca-panda-510-g",
        ],
        statementProducts: [],
        statementImage:
          "assets/brands/lee-kum-kee/wok-unsplash-clem-onojeghuo.jpg",
        statementImageAlt:
          "Cocinero preparando vegetales en un wok",
        featuredHeading: "Selección esencial",
        featuredProducts: [
          "lee-kum-kee-salsa-soya-sazonada-para-mariscos-410-ml",
          "lee-kum-kee-aceite-de-sesamo-pure-sesame-oil-270-ml",
          "lee-kum-kee-salsa-con-sabor-a-ostion-marca-panda-510-g",
        ],
        editorialImage:
          "assets/brands/lee-kum-kee/stir-fry-unsplash-frederick-shaw.jpg",
        editorialImageAlt:
          "Plato de pollo salteado con vegetales",
        editorialTitle: "Del wok a la mesa profesional.",
        editorialTitleLines: [
          "Del wok a la",
          "mesa profesional.",
        ],
        editorialText:
          "Consistencia, versatilidad y profundidad de sabor para marinados, salteados, arroces y terminaciones. Portafolio disponible para consulta comercial a través de Alzarsi.",
        catalogHeading: "Portafolio disponible",
      },
    },
    {
      id: "becoco",
      name: "BéCoco",
      logo: "assets/brands/becoco/becoco-logo-official.png",
      intro:
        "Alimentos elaborados a base de coco para recetas dulces, saladas y funcionales.",
      story:
        "Aceites, harinas, bebidas y especialidades de coco reunidas en un portafolio pensado para distintos usos culinarios.",
      cities: ["la-paz"],
      heroImage: "assets/products/becoco/chips-de-coco-sugar-and-salt-50-g.png",
      catalogStatus: "available",
      theme: {
        background: "#eef7e9",
        surface: "#ffffff",
        text: "#2f6232",
        accent: "#83c86a",
        contrast: "#69ad45",
        onContrast: "#ffffff",
      },
      presentation: {
        layout: "campaign",
        heroBanner: "assets/brands/becoco/becoco-coconut-hero-unsplash.jpg",
        heroBannerAlt: "Productos de coco sobre una mesa clara",
        heroOverlayLogo: false,
        heroWordmark: "assets/brands/becoco/becoco-wordmark-white.png",
        heroCampaignTitle: "El lado coco de cada receta.",
        heroCampaignText: "Ingredientes versátiles para cocinar, compartir y disfrutar todos los días.",
        statement: "Sé única. Sé natural. Sé BéCoco.",
        statementLines: ["Sé única.", "Sé natural.", "Sé BéCoco."],
        statementImage: "assets/brands/becoco/becoco-woman-campaign.jpg",
        statementImageAlt: "Mujer disfrutando chips de coco BéCoco",
        featuredHeading: "Esenciales de coco",
        featuredProducts: [
          "becoco-harina-de-coco-250-g",
          "becoco-aceite-de-coco-extra-virgen-prensado-en-frio-200-ml",
          "becoco-leche-de-coco-en-polvo-350-g",
        ],
        editorialImage: "assets/brands/becoco/becoco-bottom.jpg",
        editorialImageAlt: "Coco y chips de coco BéCoco",
        editorialTitle: "Un ingrediente. Muchas formas de cocinar.",
        editorialTitleLines: ["Un ingrediente.", "Muchas formas", "de cocinar."],
        editorialText: "Harinas, aceites, bebidas, snacks y especialidades de coco para aplicaciones dulces, saladas y funcionales.",
        catalogHeading: "Portafolio BéCoco",
      },
    },
    {
      id: "bioplast",
      name: "Bioplast",
      logo: "assets/brands/bioplast.png",
      intro:
        "Soluciones prácticas de limpieza, desinfección y cuidado del hogar.",
      story:
        "Productos funcionales para responder a necesidades cotidianas de higiene, limpieza y organización.",
      cities: ["la-paz"],
      heroImage: "assets/products/bioplast/desinfectante-5-l.png",
      catalogStatus: "available",
      theme: {
        background: "#edf3f0",
        surface: "#f8faf8",
        text: "#183c38",
        accent: "#02544e",
        contrast: "#02544e",
        onContrast: "#f7f8f3",
      },
      presentation: {
        layout: "editorial",
        heroLogo: "assets/brands/bioplast/bioplast-logo-white.png",
        heroBanner: "assets/brands/bioplast/bioplast-hero-unsplash.jpg",
        heroBannerAlt: "Bolsas translúcidas fotografiadas sobre una superficie clara",
        heroHeadlineLines: ["Soluciones", "prácticas para", "cada operación."],
        statementLines: ["Bolsas que", "acompañan tu hogar."],
        statementImage: "assets/brands/bioplast/bioplast-bags-unsplash.jpg",
        statementImageAlt: "Bolsas de papel para compras y uso cotidiano",
        featuredHeading: "Soluciones disponibles",
        featuredProducts: [
          "bioplast-desinfectante-5-l",
          "bioplast-superior-bolsa-de-basura-mediana-60-x-65-cm-35-l",
          "bioplast-lavandina-dona-clarita-1-l",
        ],
        editorialImage: "assets/brands/bioplast/bioplast-home-unsplash.jpg",
        editorialImageAlt: "Familia organizando productos para el hogar",
        editorialTitleLines: ["Cuidar también", "es hacer hogar."],
        editorialText: "Soluciones prácticas para mantener los espacios limpios, ordenados y listos para disfrutarse.",
        catalogHeading: "Portafolio BioPlast",
      },
    },
    {
      id: "arrozame",
      name: "Arrozame",
      logo: "assets/brands/arrozame.png",
      intro:
        "Bases y preparaciones seleccionadas para paellas y cocina mediterránea.",
      story:
        "Ingredientes que simplifican la preparación y ayudan a mantener un resultado consistente en cada servicio.",
      cities: ["santa-cruz"],
      heroImage: "assets/products/arrozame/fondo-de-pescado-paelalia-525-g.png",
      catalogStatus: "available",
    },
    {
      id: "sanoryza",
      name: "Sanoryza",
      logo: "assets/brands/sanoryza.png",
      intro:
        "Fideos de arroz y quinua para una cocina ligera, práctica y versátil.",
      story:
        "Alternativas para hogares y cocinas profesionales que buscan nuevas texturas y preparaciones sencillas.",
      cities: ["santa-cruz"],
      heroImage: "assets/products/sanoryza/fideo-de-arroz-grueso-300g.png",
      catalogStatus: "available",
    },
    {
      id: "te-chapare",
      name: "Té Chapare",
      logo: "assets/brands/te-chapare.png",
      intro:
        "Infusiones bolivianas en distintas presentaciones y combinaciones.",
      story:
        "Una selección de tés e infusiones para acompañar distintos momentos del día.",
      cities: ["santa-cruz"],
      heroImage: "assets/products/te-chapare/te-verde-ecologico-20-sobres.png",
      catalogStatus: "available",
      theme: {
        background: "#eef0e5",
        surface: "#f8f6e9",
        text: "#24392b",
        accent: "#f1ba00",
        contrast: "#315b3a",
        onContrast: "#fff9df",
      },
      presentation: {
        layout: "campaign",
        heroBanner: "assets/brands/te-chapare/te-chapare-hero.jpg",
        heroBannerAlt: "Taza e infusiones de Té Chapare",
        heroOverlayLogo: false,
        heroCampaignTitle: "Una pausa que nos reúne.",
        heroCampaignText: "Infusiones bolivianas para compartir en familia.",
        statementLines: ["Una pausa", "para compartir."],
        statementImage: "assets/brands/te-chapare/tea-vector-unsplash.jpg",
        statementImageAlt: "Ilustración editorial de una taza de té",
        featuredHeading: "Selección de infusiones",
        featuredProducts: [
          "te-chapare-te-verde-ecologico-20-sobres",
          "te-chapare-te-verde-con-pina-20-unidades",
          "te-chapare-te-negro-ecologico-20-unidades",
        ],
        editorialImage: "assets/brands/te-chapare/tea-pouring-unsplash.jpg",
        editorialImageAlt: "Té servido desde una tetera de vidrio",
        editorialTitleLines: ["Calidez en", "cada taza."],
        editorialText: "Tés verdes, negros e infusiones bolivianas para acompañar conversaciones, sobremesas y momentos en familia.",
        catalogHeading: "Portafolio Té Chapare",
      },
    },
    {
      id: "el-cazador",
      name: "El Cazador",
      logo: "assets/brands/el-cazador/el-cazador-logo-trimmed.png",
      intro:
        "Arroces seleccionados para preparaciones de gran formato y cocina especializada.",
      story:
        "Una selección de arroz valenciano pensada para lograr textura, rendimiento y consistencia en paellas y preparaciones de gran formato.",
      cities: ["la-paz", "santa-cruz"],
      heroImage: "assets/products/el-cazador/arroz-de-paella-1-kg.png",
      catalogStatus: "available",
      theme: {
        background: "#e9dece",
        surface: "#f8f3ea",
        text: "#49231f",
        accent: "#781f26",
        contrast: "#6b4a37",
        onContrast: "#fffaf1",
      },
      presentation: {
        layout: "campaign",
        heroBanner: "assets/brands/el-cazador/el-cazador-valencia-stairs-hero.jpg",
        heroBannerAlt: "Escalinata tradicional en Valencia, España",
        heroOverlayLogo: false,
        heroCampaignTitle: "De Valencia a tu mesa.",
        heroCampaignText: "Tradición arrocera, rendimiento y textura para preparaciones que reúnen a todos alrededor de la mesa.",
        statementLines: ["Textura que", "reúne."],
        statementImage: "assets/brands/el-cazador/valencia-rice-unsplash.jpg",
        statementImageAlt: "Campos de arroz de Valencia",
        featuredHeading: "Producto disponible",
        featuredProducts: ["el-cazador-arroz-de-paella-1-kg"],
        editorialImage: "assets/brands/el-cazador/rice-tradition-unsplash.jpg",
        editorialImageAlt: "Cultivo tradicional de arroz",
        editorialTitleLines: ["Una tradición", "de más de", "cien años."],
        editorialText: "La marca nace de una tradición agrícola generacional en Valencia, cuna del cultivo europeo del arroz.",
        catalogHeading: "Portafolio El Cazador",
      },
    },
    {
      id: "kikko",
      name: "Kikko",
      logo: "assets/brands/kikko.png",
      intro:
        "Portafolio de salsas orientales para cocinas profesionales, comercio y consumo en el hogar.",
      story:
        "Perfiles consistentes para marinados, salteados, arroces y terminaciones. Una selección versátil para operaciones gastronómicas y distintos formatos de cocina.",
      cities: [],
      heroImage: "assets/products/kikko/siyau-original.png",
      catalogStatus: "available",
      theme: {
        background: "#f5d85c",
        surface: "#fff8e9",
        text: "#24231f",
        accent: "#d82e38",
        contrast: "#11110f",
        onContrast: "#fff6e4",
      },
      presentation: {
        heroBanner:
          "assets/brands/kikko/kikko-hero-portrait.png",
        heroBannerAlt:
          "Salsa de soya Kikko con arroz, huevos, cebollín, jengibre y pimentón",
        heroHeadline: "El sabor que transforma cada preparación.",
        heroHeadlineLines: [
          "El sabor que",
          "transforma",
          "cada preparación.",
        ],
        statement: "Sabores orientales hechos para compartir.",
        statementLines: [
          "Sabores orientales",
          "hechos para",
          "compartir.",
        ],
        heroProducts: [
          "kikko-salsa-mensi",
          "kikko-siyau-original",
          "kikko-ajoikion",
        ],
        statementProducts: [],
        statementImage:
          "assets/brands/kikko/fried-rice-gourmet-unsplash-lee-milo.jpg",
        statementImageAlt:
          "Arroz frito presentado en un plato de restaurante",
        featuredHeading: "Selección del portafolio",
        featuredProducts: [
          "kikko-siyau-original",
          "kikko-salsa-mensi",
          "kikko-ajoikion",
        ],
        editorialImage:
          "assets/brands/kikko/fried-rice-unsplash-amanda-lim.jpg",
        editorialImageAlt: "Arroz frito chino con mariscos",
        editorialTitle: "Tradición que encuentra nuevas cocinas.",
        editorialTitleLines: [
          "Tradición que",
          "encuentra nuevas",
          "cocinas.",
        ],
        editorialText:
          "Soluciones versátiles para arroces, marinados, salteados y terminaciones, disponibles para consulta comercial a través de Alzarsi.",
        catalogHeading: "Portafolio disponible",
      },
    },
    {
      id: "saborati",
      name: "Saborati",
      logo: "assets/brands/saborati.png",
      intro: "Especialidades gourmet elaboradas en Tarija con ingredientes locales e inspiración italiana.",
      story: "Recetas de pequeña escala que combinan ingredientes tarijeños, cultivos del Jardín Saborati y técnicas aprendidas en Europa.",
      cities: ["santa-cruz"],
      heroImage: "assets/products/saborati/pesto-chapaco.jpg",
      catalogStatus: "available",
      theme: {
        background: "#f2eee4",
        surface: "#fbf8f1",
        text: "#302b28",
        accent: "#e11c23",
        contrast: "#516b3b",
        onContrast: "#fff9ed",
      },
      presentation: {
        layout: "editorial",
        heroBanner: "assets/products/saborati/ajies-aceite.png",
        heroBannerAlt: "Ajíes al aceite elaborados por Saborati",
        heroHeadlineLines: ["Sabores de", "Tarija con", "oficio propio."],
        statementLines: ["Origen local.", "Inspiración", "gourmet."],
        statementImage: "assets/products/saborati/crema-chuflay.jpg",
        statementImageAlt: "Selección artesanal de productos Saborati",
        featuredHeading: "Especialidades Saborati",
        featuredProducts: [
          "saborati-sal-ahumada",
          "saborati-pesto-chapaco",
          "saborati-ajies-al-aceite",
        ],
        editorialImage: "assets/products/saborati/limoncello.png",
        editorialImageAlt: "Limoncello Saborati",
        editorialTitleLines: ["Productos con", "historia, huerta", "y territorio."],
        editorialText: "Sales, conservas, licores y salsas nacidas de una fabricación local que pone en primer plano los ingredientes y sabores de Tarija.",
        catalogHeading: "Línea Saborati",
      },
    },
    {
      id: "roland-foods",
      name: "Roland Foods",
      logo: "assets/brands/roland-foods.png",
      intro:
        "Ingredientes internacionales para cocinas profesionales y comercios.",
      story:
        "Una casa de ingredientes especializados fundada en 1934, con un catálogo internacional pensado para cocinas profesionales y comercio.",
      cities: [],
      heroImage: "assets/products/roland-foods/organic-hearts-of-palm.png",
      catalogStatus: "available",
      theme: {
        background: "#efece2",
        surface: "#faf8f1",
        text: "#302f2a",
        accent: "#9e7917",
        contrast: "#565a45",
        onContrast: "#fffdf4",
      },
      presentation: {
        layout: "campaign",
        heroBanner: "assets/brands/roland-foods/roland-campaign-hero.jpg",
        heroBannerAlt: "Selección ilustrada de productos Roland Foods",
        heroOverlayLogo: true,
        statementLines: ["Ingredientes", "globales para", "cocinas actuales."],
        statementImage: "assets/brands/roland-foods/roland-hearts-editorial.png",
        statementImageAlt: "Selección oficial de palmitos Roland Foods",
        featuredHeading: "Selección internacional",
        featuredProducts: [
          "roland-organic-hearts-of-palm-14-46-oz",
          "roland-sambal-oelek-8-oz",
          "roland-sardines-olive-oil-4-4-oz",
        ],
        editorialImage: "assets/brands/roland-foods/roland-chili-editorial.png",
        editorialImageAlt: "Selección oficial de salsas picantes Roland Foods",
        editorialTitleLines: ["El mundo", "servido en", "una cocina."],
        editorialText: "Vegetales, granos, conservas, salsas y especialidades internacionales seleccionadas para ampliar las posibilidades del canal gastronómico.",
        catalogHeading: "Selección Roland Foods",
      },
    },
  ],
  products: [
    {
      id: "kikko-siyau-original",
      brand: "kikko",
      name: "Siyau Original",
      category: "Salsas y condimentos",
      size: null,
      cities: [],
      image: "assets/products/kikko/siyau-original.png",
      barcode: null,
      caseQuantity: null,
      active: true,
      description:
        "Salsa de soya clásica, elaborada con soya seleccionada y fermentada naturalmente.",
      featureText:
        "Perfil de soya para arroces, marinados y salteados de operación continua.",
    },
    {
      id: "kikko-salsa-mensi",
      brand: "kikko",
      name: "Salsa Mensi",
      category: "Salsas y condimentos",
      size: null,
      cities: [],
      image: "assets/products/kikko/salsa-mensi.png",
      barcode: null,
      caseQuantity: null,
      active: true,
      description:
        "Salsa especial elaborada con ingredientes seleccionados y un perfil de sabor característico.",
      featureText:
        "Aplicación versátil en carnes, vegetales y preparaciones al horno.",
    },
    {
      id: "kikko-ajoikion",
      brand: "kikko",
      name: "Ajoikion",
      category: "Salsas y condimentos",
      size: null,
      cities: [],
      image: "assets/products/kikko/ajoikion.png",
      barcode: null,
      caseQuantity: null,
      active: true,
      description:
        "Fusión de salsa de soya con ajo y kion para marinados, salteados y platos orientales.",
      featureText:
        "Soya, ajo y kion para marinados, salteados y terminaciones aromáticas.",
    },
    {
      id: "kikko-shoyu-premium",
      brand: "kikko",
      name: "Shoyu Premium",
      category: "Salsas y condimentos",
      size: null,
      cities: [],
      image: "assets/products/kikko/shoyu-premium.png",
      barcode: null,
      caseQuantity: null,
      active: true,
      description:
        "Salsa shoyu de calidad superior con un sabor refinado y complejo.",
    },
    {
      id: "kikko-salsa-wantan",
      brand: "kikko",
      name: "Salsa Wantán",
      category: "Salsas y condimentos",
      size: null,
      cities: [],
      image: "assets/products/kikko/salsa-wantan.png",
      barcode: null,
      caseQuantity: null,
      active: true,
      description:
        "Salsa agridulce de tamarindo con equilibrio entre acidez natural y dulzor.",
    },
    {
      id: "lee-kum-kee-salsa-soya-sazonada-para-mariscos-410-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya sazonada para mariscos",
      category: "Salsas y condimentos",
      size: "410 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-sazonada-para-mariscos-410-ml.png",
      barcode: "78895423037",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-aceite-de-sesamo-pure-sesame-oil-270-ml",
      brand: "lee-kum-kee",
      name: "Aceite de sésamo (Pure Sesame Oil)",
      category: "Salsas y condimentos",
      size: "270 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/aceite-de-sesamo-pure-sesame-oil-270-ml.png",
      barcode: "7889571092",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-aceite-de-sesamo-pure-sesame-oil-1-65-l",
      brand: "lee-kum-kee",
      name: "Aceite de sésamo (Pure Sesame Oil)",
      category: "Salsas y condimentos",
      size: "1.65 L",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/aceite-de-sesamo-pure-sesame-oil-1-65-l.png",
      barcode: "78895150827",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-dispensador-de-mesa-150-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya dispensador de mesa",
      category: "Salsas y condimentos",
      size: "150 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-dispensador-de-mesa-150-ml.png",
      barcode: "78895128833",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-calidad-superior-500-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya calidad superior",
      category: "Salsas y condimentos",
      size: "500 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-calidad-superior-500-ml.png",
      barcode: "78895126396",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-calidad-superior-15-kg",
      brand: "lee-kum-kee",
      name: "Salsa soya calidad superior",
      category: "Salsas y condimentos",
      size: "15 kg",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-calidad-superior-15-kg.png",
      barcode: "78895132502",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-oscura-superior-15-kg",
      brand: "lee-kum-kee",
      name: "Salsa soya oscura superior",
      category: "Salsas y condimentos",
      size: "15 kg",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-soya-oscura-superior-15-kg.png",
      barcode: "78895132496",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-oscura-calidad-superior-500-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya oscura calidad superior",
      category: "Salsas y condimentos",
      size: "500 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-oscura-calidad-superior-500-ml.png",
      barcode: "78895127973",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-light-500-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya light",
      category: "Salsas y condimentos",
      size: "500 ml",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-soya-light-500-ml.png",
      barcode: "78895130188",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-light-150-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya light",
      category: "Salsas y condimentos",
      size: "150 ml",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-soya-light-150-ml.png",
      barcode: "78895131413",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-oscura-sabor-champinon-15-kg",
      brand: "lee-kum-kee",
      name: "Salsa soya oscura sabor champiñón",
      category: "Salsas y condimentos",
      size: "15 kg",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-oscura-sabor-champinon-15-kg.png",
      barcode: "78895132489",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-soya-oscura-sabor-champinon-500-ml",
      brand: "lee-kum-kee",
      name: "Salsa soya oscura sabor champiñón",
      category: "Salsas y condimentos",
      size: "500 ml",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-soya-oscura-sabor-champinon-500-ml.png",
      barcode: "78895128895",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-estilo-teriyaki-250-ml",
      brand: "lee-kum-kee",
      name: "Salsa estilo teriyaki",
      category: "Salsas y condimentos",
      size: "250 ml",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-estilo-teriyaki-250-ml.png",
      barcode: "78895120509",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-agridulce-240-ml",
      brand: "lee-kum-kee",
      name: "Salsa agridulce",
      category: "Salsas y condimentos",
      size: "240 ml",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-agridulce-240-ml.png",
      barcode: "78895720051",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-dulce-tailandesa-de-chile-510-g",
      brand: "lee-kum-kee",
      name: "Salsa dulce tailandesa de chile",
      category: "Salsas y condimentos",
      size: "510 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-dulce-tailandesa-de-chile-510-g.png",
      barcode: "78895131024",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-marinado-de-pollo-estilo-teriyaki-410-g",
      brand: "lee-kum-kee",
      name: "Marinado de pollo estilo teriyaki",
      category: "Salsas y condimentos",
      size: "410 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/marinado-de-pollo-estilo-teriyaki-410-g.png",
      barcode: "78895800319",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-barbacoa-estilo-coreano-370-g",
      brand: "lee-kum-kee",
      name: "Salsa barbacoa estilo coreano",
      category: "Salsas y condimentos",
      size: "370 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-barbacoa-estilo-coreano-370-g.png",
      barcode: "78895129816",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-picante-de-ajos-368-g",
      brand: "lee-kum-kee",
      name: "Salsa picante de ajos",
      category: "Salsas y condimentos",
      size: "368 g",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-picante-de-ajos-368-g.png",
      barcode: "78895770025",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-con-sabor-a-ostion-marca-panda-510-g",
      brand: "lee-kum-kee",
      name: "Salsa con sabor a ostión marca Panda",
      category: "Salsas y condimentos",
      size: "510 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-con-sabor-a-ostion-marca-panda-510-g.png",
      barcode: "78895300024",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-con-sabor-a-ostion-marca-panda-255-g",
      brand: "lee-kum-kee",
      name: "Salsa con sabor a ostión marca Panda",
      category: "Salsas y condimentos",
      size: "255 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-con-sabor-a-ostion-marca-panda-255-g.png",
      barcode: "78895300017",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-con-sabor-a-ostion-marca-panda-2-268-g",
      brand: "lee-kum-kee",
      name: "Salsa con sabor a ostión marca Panda",
      category: "Salsas y condimentos",
      size: "2,268 g",
      cities: ["la-paz", "santa-cruz"],
      image:
        "assets/products/lee-kum-kee/salsa-con-sabor-a-ostion-marca-panda-2-268-g.png",
      barcode: "78895300048",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-hoisin-2-268-g",
      brand: "lee-kum-kee",
      name: "Salsa Hoisin",
      category: "Salsas y condimentos",
      size: "2,268 g",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-hoisin-2-268-g.png",
      barcode: "78895700053",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-hoisin-397-g",
      brand: "lee-kum-kee",
      name: "Salsa Hoisin",
      category: "Salsas y condimentos",
      size: "397 g",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-hoisin-397-g.png",
      barcode: "78895700022",
      caseQuantity: null,
      active: true,
    },
    {
      id: "lee-kum-kee-salsa-curry-235-g",
      brand: "lee-kum-kee",
      name: "Salsa Curry",
      category: "Salsas y condimentos",
      size: "235 g",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/lee-kum-kee/salsa-curry-235-g.png",
      barcode: "78895610123",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-chips-de-coco-sugar-and-salt-50-g",
      brand: "becoco",
      name: "Chips de coco Sugar and Salt",
      category: "Productos de coco",
      size: "50 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/chips-de-coco-sugar-and-salt-50-g.png",
      barcode: "7772622340040",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-chips-de-coco-sugar-and-salt-250-g",
      brand: "becoco",
      name: "Chips de coco Sugar and Salt",
      category: "Productos de coco",
      size: "250 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/chips-de-coco-sugar-and-salt-250-g.png",
      barcode: "7772622340118",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-chips-de-coco-toasted-50-g",
      brand: "becoco",
      name: "Chips de coco Toasted",
      category: "Productos de coco",
      size: "50 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/chips-de-coco-toasted-50-g.png",
      barcode: "7772622340132",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-chips-de-coco-toasted-250-g",
      brand: "becoco",
      name: "Chips de coco Toasted",
      category: "Productos de coco",
      size: "250 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/chips-de-coco-toasted-250-g.png",
      barcode: "7772622340057",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-mantequilla-de-coco-200-ml",
      brand: "becoco",
      name: "Mantequilla de coco",
      category: "Productos de coco",
      size: "200 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/mantequilla-de-coco-200-ml.png",
      barcode: "7772622340101",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-syrup-de-coco-350-g",
      brand: "becoco",
      name: "Syrup de coco",
      category: "Productos de coco",
      size: "350 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/syrup-de-coco-350-g.png",
      barcode: "7772622340071",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-harina-de-coco-250-g",
      brand: "becoco",
      name: "Harina de coco",
      category: "Productos de coco",
      size: "250 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/harina-de-coco-250-g.png",
      barcode: "7772622340019",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-harina-de-coco-1-kg",
      brand: "becoco",
      name: "Harina de coco",
      category: "Productos de coco",
      size: "1 kg",
      cities: ["la-paz"],
      image: "assets/products/becoco/harina-de-coco-1-kg.png",
      barcode: "7772622340163",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-azucar-de-coco-250-g",
      brand: "becoco",
      name: "Azúcar de coco",
      category: "Productos de coco",
      size: "250 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/azucar-de-coco-250-g.png",
      barcode: "7772622340187",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-azucar-de-coco-1-kg",
      brand: "becoco",
      name: "Azúcar de coco",
      category: "Productos de coco",
      size: "1 kg",
      cities: ["la-paz"],
      image: "assets/products/becoco/azucar-de-coco-1-kg.png",
      barcode: "7772622340088",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-leche-de-coco-en-polvo-100-g",
      brand: "becoco",
      name: "Leche de coco en polvo",
      category: "Productos de coco",
      size: "100 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/leche-de-coco-en-polvo-100-g.png",
      barcode: "7772622340095",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-leche-de-coco-en-polvo-350-g",
      brand: "becoco",
      name: "Leche de coco en polvo",
      category: "Productos de coco",
      size: "350 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/leche-de-coco-en-polvo-350-g.png",
      barcode: "7772622340170",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-leche-de-coco-en-polvo-1-kg",
      brand: "becoco",
      name: "Leche de coco en polvo",
      category: "Productos de coco",
      size: "1 kg",
      cities: ["la-paz"],
      image: "assets/products/becoco/leche-de-coco-en-polvo-1-kg.png",
      barcode: "7772622340279",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-extra-virgen-prensado-en-frio-200-ml",
      brand: "becoco",
      name: "Aceite de coco extra virgen prensado en frío",
      category: "Productos de coco",
      size: "200 ml",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/aceite-de-coco-extra-virgen-prensado-en-frio-200-ml.png",
      barcode: "7772622340194",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-extra-virgen-prensado-en-frio-720-ml",
      brand: "becoco",
      name: "Aceite de coco extra virgen prensado en frío",
      category: "Productos de coco",
      size: "720 ml",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/aceite-de-coco-extra-virgen-prensado-en-frio-720-ml.png",
      barcode: "7772622340026",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-extra-virgen-prensado-en-frio-por-expulsor-200-ml",
      brand: "becoco",
      name: "Aceite de coco extra virgen prensado en frío por expulsor",
      category: "Productos de coco",
      size: "200 ml",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/aceite-de-coco-extra-virgen-prensado-en-frio-por-expulsor-200-ml.png",
      barcode: "7772622340217",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-extra-virgen-prensado-en-frio-por-expulsor-720-ml",
      brand: "becoco",
      name: "Aceite de coco extra virgen prensado en frío por expulsor",
      category: "Productos de coco",
      size: "720 ml",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/aceite-de-coco-extra-virgen-prensado-en-frio-por-expulsor-720-ml.png",
      barcode: "7772622340224",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-culinario-3-6-l",
      brand: "becoco",
      name: "Aceite de coco culinario",
      category: "Productos de coco",
      size: "3.6 L",
      cities: ["la-paz"],
      image: "assets/products/becoco/aceite-de-coco-culinario-3-6-l.png",
      barcode: "7772622340156",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-culinario-370-ml",
      brand: "becoco",
      name: "Aceite de coco culinario",
      category: "Productos de coco",
      size: "370 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/aceite-de-coco-culinario-370-ml.png",
      barcode: "7772622340064",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-culinario-720-ml",
      brand: "becoco",
      name: "Aceite de coco culinario",
      category: "Productos de coco",
      size: "720 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/aceite-de-coco-culinario-720-ml.png",
      barcode: "7772622340033",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-aceite-de-coco-mct-500-ml",
      brand: "becoco",
      name: "Aceite de coco MCT",
      category: "Productos de coco",
      size: "500 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/aceite-de-coco-mct-500-ml.png",
      barcode: "7772622340248",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-leche-condensada-de-coco-210-g",
      brand: "becoco",
      name: "Leche condensada de coco",
      category: "Productos de coco",
      size: "210 g",
      cities: ["la-paz"],
      image: "assets/products/becoco/leche-condensada-de-coco-210-g.png",
      barcode: "4792103003656",
      caseQuantity: "12",
      active: true,
    },
    {
      id: "becoco-leche-condensada-de-coco-sabor-vainilla-210-g",
      brand: "becoco",
      name: "Leche condensada de coco sabor vainilla",
      category: "Productos de coco",
      size: "210 g",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/leche-condensada-de-coco-sabor-vainilla-210-g.png",
      barcode: "4792103002345",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-leche-condensada-de-coco-sabor-cafe-210-g",
      brand: "becoco",
      name: "Leche condensada de coco sabor café",
      category: "Productos de coco",
      size: "210 g",
      cities: ["la-paz"],
      image:
        "assets/products/becoco/leche-condensada-de-coco-sabor-cafe-210-g.png",
      barcode: "4792103002390",
      caseQuantity: null,
      active: true,
    },
    {
      id: "becoco-crema-de-coco-para-batir-400-ml",
      brand: "becoco",
      name: "Crema de coco para batir",
      category: "Productos de coco",
      size: "400 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/crema-de-coco-para-batir-400-ml.png",
      barcode: "4792103003663",
      caseQuantity: "12",
      active: true,
    },
    {
      id: "becoco-coconut-aminos-salsa-sin-soya-250-ml",
      brand: "becoco",
      name: "Coconut Aminos, salsa sin soya",
      category: "Productos de coco",
      size: "250 ml",
      cities: ["la-paz"],
      image: "assets/products/becoco/coconut-aminos-salsa-sin-soya-250-ml.png",
      barcode: "4792103003649",
      caseQuantity: "12",
      active: true,
    },
    {
      id: "bioplast-desinfectante-5-l",
      brand: "bioplast",
      name: "Desinfectante",
      category: "Limpieza y hogar",
      size: "5 L",
      cities: ["la-paz"],
      image: "assets/products/bioplast/desinfectante-5-l.png",
      barcode: "7793253091880",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-desinfectante-dona-clarita-250-ml",
      brand: "bioplast",
      name: "Desinfectante Doña Clarita",
      category: "Limpieza y hogar",
      size: "250 ml",
      cities: ["la-paz"],
      image: "assets/products/bioplast/desinfectante-dona-clarita-250-ml.png",
      barcode: "7793253091859",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-dona-clarita-desinfectante-blanqueador-1-l",
      brand: "bioplast",
      name: "Doña Clarita desinfectante blanqueador",
      category: "Limpieza y hogar",
      size: "1 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/dona-clarita-desinfectante-blanqueador-1-l.png",
      barcode: "7793253091873",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-lavandina-dona-clarita-1-l",
      brand: "bioplast",
      name: "Lavandina Doña Clarita",
      category: "Limpieza y hogar",
      size: "1 L",
      cities: ["la-paz"],
      image: "assets/products/bioplast/lavandina-dona-clarita-1-l.png",
      barcode: "7793253091873",
      caseQuantity: 12,
      active: true,
    },
    {
      id: "bioplast-lavandina-dona-clarita-caja-x12-1-l",
      brand: "bioplast",
      name: "Lavandina Doña Clarita (caja x12)",
      category: "Limpieza y hogar",
      size: "1 L",
      cities: ["la-paz"],
      image: "assets/products/bioplast/lavandina-dona-clarita-caja-x12-1-l.png",
      barcode: "10039",
      caseQuantity: 12,
      active: true,
    },
    {
      id: "bioplast-pack-desinfectante-dona-clarita-2-x-1-l",
      brand: "bioplast",
      name: "Pack desinfectante Doña Clarita",
      category: "Limpieza y hogar",
      size: "2 x 1 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/pack-desinfectante-dona-clarita-2-x-1-l.png",
      barcode: "7793253091842N",
      caseQuantity: 2,
      active: true,
    },
    {
      id: "bioplast-lavandina-mr-cloro-sachet-250-ml",
      brand: "bioplast",
      name: "Lavandina Mr Cloro sachet",
      category: "Limpieza y hogar",
      size: "250 ml",
      cities: ["la-paz"],
      image: "assets/products/bioplast/lavandina-mr-cloro-sachet-250-ml.png",
      barcode: "7779970700014",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-lavandina-mr-cloro-1-l",
      brand: "bioplast",
      name: "Lavandina Mr. Cloro",
      category: "Limpieza y hogar",
      size: "1 L",
      cities: ["la-paz"],
      image: "assets/products/bioplast/lavandina-mr-cloro-1-l.png",
      barcode: "7779970700038",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-superior-bolsa-de-basura-pequena-55-x-50-cm-25-l",
      brand: "bioplast",
      name: "Superior bolsa de basura pequeña",
      category: "Limpieza y hogar",
      size: "55 x 50 cm / 25 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/superior-bolsa-de-basura-pequena-55-x-50-cm-25-l.png",
      barcode: "none",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-superior-bolsa-de-basura-mediana-60-x-65-cm-35-l",
      brand: "bioplast",
      name: "Superior bolsa de basura mediana",
      category: "Limpieza y hogar",
      size: "60 x 65 cm / 35 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/superior-bolsa-de-basura-mediana-60-x-65-cm-35-l.png",
      barcode: "7775602110022",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-superior-bolsa-de-basura-grande-70-x-80-cm-50-l",
      brand: "bioplast",
      name: "Superior bolsa de basura grande",
      category: "Limpieza y hogar",
      size: "70 x 80 cm / 50 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/superior-bolsa-de-basura-grande-70-x-80-cm-50-l.png",
      barcode: "777562110039",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-superior-bolsa-de-basura-extra-grande-75-x-95-cm-75-l",
      brand: "bioplast",
      name: "Superior bolsa de basura extra grande",
      category: "Limpieza y hogar",
      size: "75 x 95 cm / 75 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/superior-bolsa-de-basura-extra-grande-75-x-95-cm-75-l.png",
      barcode: "7775602110046",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-superior-bolsa-de-basura-gigante-90-x-110-cm-140-l",
      brand: "bioplast",
      name: "Superior bolsa de basura gigante",
      category: "Limpieza y hogar",
      size: "90 x 110 cm / 140 L",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/superior-bolsa-de-basura-gigante-90-x-110-cm-140-l.png",
      barcode: "7775602110053",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-basulip-bolsa-para-basura-grande-80-x-110-cm",
      brand: "bioplast",
      name: "Basulip bolsa para basura grande",
      category: "Limpieza y hogar",
      size: "80 x 110 cm",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/basulip-bolsa-para-basura-grande-80-x-110-cm.png",
      barcode: "10034",
      caseQuantity: null,
      active: true,
    },
    {
      id: "bioplast-basulip-bolsa-para-basura-mediana-70-x-90-cm",
      brand: "bioplast",
      name: "Basulip bolsa para basura mediana",
      category: "Limpieza y hogar",
      size: "70 x 90 cm",
      cities: ["la-paz"],
      image:
        "assets/products/bioplast/basulip-bolsa-para-basura-mediana-70-x-90-cm.png",
      barcode: "10033",
      caseQuantity: null,
      active: true,
    },
    {
      id: "arrozame-fondo-de-pescado-paelalia-525-g",
      brand: "arrozame",
      name: "Fondo de pescado Paelalia",
      category: "Ingredientes para paella",
      size: "525 g",
      cities: ["santa-cruz"],
      image: "assets/products/arrozame/fondo-de-pescado-paelalia-525-g.png",
      barcode: "843701527113",
      caseQuantity: null,
      active: true,
    },
    {
      id: "arrozame-salmorreta-marisqueria-arrozame-200g",
      brand: "arrozame",
      name: "Salmorreta Marisquería Arrozame",
      category: "Ingredientes para paella",
      size: "200g",
      cities: ["santa-cruz"],
      image:
        "assets/products/arrozame/salmorreta-marisqueria-arrozame-200g.png",
      barcode: "843701527220",
      caseQuantity: null,
      active: true,
    },
    {
      id: "sanoryza-fideo-de-arroz-grueso-300g",
      brand: "sanoryza",
      name: "Fideo de arroz grueso",
      category: "Fideos de arroz y quinua",
      size: "300g",
      cities: ["santa-cruz"],
      image: "assets/products/sanoryza/fideo-de-arroz-grueso-300g.png",
      barcode: "7771430220049",
      caseQuantity: null,
      active: true,
    },
    {
      id: "sanoryza-fideo-de-arroz-delgado-300g",
      brand: "sanoryza",
      name: "Fideo de arroz delgado",
      category: "Fideos de arroz y quinua",
      size: "300g",
      cities: ["santa-cruz"],
      image: "assets/products/sanoryza/fideo-de-arroz-delgado-300g.png",
      barcode: "7771430220018",
      caseQuantity: null,
      active: true,
    },
    {
      id: "sanoryza-fideo-de-quinua-delgado-300g",
      brand: "sanoryza",
      name: "Fideo de quinua delgado",
      category: "Fideos de arroz y quinua",
      size: "300g",
      cities: ["santa-cruz"],
      image: "assets/products/sanoryza/fideo-de-quinua-delgado-300g.png",
      barcode: "777143022025",
      caseQuantity: null,
      active: true,
    },
    {
      id: "te-chapare-te-verde-ecologico-20-sobres",
      brand: "te-chapare",
      name: "Té verde ecológico",
      category: "Tés e infusiones",
      size: "20 sobres",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-verde-ecologico-20-sobres.png",
      barcode: "7771817230029",
      caseQuantity: "20",
      active: true,
    },
    {
      id: "te-chapare-te-verde-ecologico-en-bolsa-50-sobres",
      brand: "te-chapare",
      name: "Té verde ecológico en bolsa",
      category: "Tés e infusiones",
      size: "50 sobres",
      cities: ["santa-cruz"],
      image:
        "assets/products/te-chapare/te-verde-ecologico-en-bolsa-50-sobres.png",
      barcode: "7771817230012",
      caseQuantity: "50",
      active: true,
    },
    {
      id: "te-chapare-te-verde-ecologico-en-hojas-50-g",
      brand: "te-chapare",
      name: "Té verde ecológico en hojas",
      category: "Tés e infusiones",
      size: "50 g",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-verde-ecologico-en-hojas-50-g.png",
      barcode: "7771817230036",
      caseQuantity: null,
      active: true,
    },
    {
      id: "te-chapare-te-verde-ecologico-en-hojas-200-g",
      brand: "te-chapare",
      name: "Té verde ecológico en hojas",
      category: "Tés e infusiones",
      size: "200 g",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-verde-ecologico-en-hojas-200-g.png",
      barcode: "7771817230098",
      caseQuantity: null,
      active: true,
    },
    {
      id: "te-chapare-te-verde-con-stevia-20-g",
      brand: "te-chapare",
      name: "Té verde con stevia",
      category: "Tés e infusiones",
      size: "20 g",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-verde-con-stevia-20-g.png",
      barcode: "7771817230143",
      caseQuantity: "20",
      active: true,
    },
    {
      id: "te-chapare-te-verde-con-pina-20-unidades",
      brand: "te-chapare",
      name: "Té verde con piña",
      category: "Tés e infusiones",
      size: "20 unidades",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-verde-con-pina-20-unidades.png",
      barcode: "7771817230181",
      caseQuantity: "20",
      active: true,
    },
    {
      id: "te-chapare-te-negro-ecologico-20-unidades",
      brand: "te-chapare",
      name: "Té negro ecológico",
      category: "Tés e infusiones",
      size: "20 unidades",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/te-negro-ecologico-20-unidades.png",
      barcode: "7771817230050",
      caseQuantity: "20",
      active: true,
    },
    {
      id: "te-chapare-manzanilla-20-unidades",
      brand: "te-chapare",
      name: "Manzanilla",
      category: "Tés e infusiones",
      size: "20 unidades",
      cities: ["santa-cruz"],
      image: "assets/products/te-chapare/manzanilla-20-unidades.png",
      barcode: "7771817230111",
      caseQuantity: "20",
      active: true,
    },
    {
      id: "el-cazador-arroz-de-paella-1-kg",
      brand: "el-cazador",
      name: "Arroz de paella",
      category: "Arroces",
      size: "1 kg",
      cities: ["la-paz", "santa-cruz"],
      image: "assets/products/el-cazador/arroz-de-paella-1-kg.png",
      barcode: "8412305123063",
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-sal-ahumada",
      brand: "saborati",
      name: "Sal ahumada",
      category: "Sales gourmet",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/sal-ahumada.jpg",
      featureText: "Sal gourmet de fabricación local desarrollada por Saborati en Tarija.",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-sal-con-limon",
      brand: "saborati",
      name: "Sal con limón",
      category: "Sales gourmet",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/sal-con-limon.png",
      featureText: "Sal fina del Salar de Uyuni con limón orgánico, romero y pimienta.",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-limoncello",
      brand: "saborati",
      name: "Limoncello",
      category: "Licores artesanales",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/limoncello.png",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-crema-de-chuflay",
      brand: "saborati",
      name: "Crema de Chuflay",
      category: "Licores artesanales",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/crema-chuflay.jpg",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-ajies-al-aceite",
      brand: "saborati",
      name: "Ajíes al aceite",
      category: "Conservas gourmet",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/ajies-aceite.png",
      featureText: "Ajíes seleccionados y conservados en aceite para aperitivos y cocina.",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "saborati-pesto-chapaco",
      brand: "saborati",
      name: "Pesto Chapaco",
      category: "Salsas gourmet",
      size: null,
      cities: ["santa-cruz"],
      image: "assets/products/saborati/pesto-chapaco.jpg",
      featureText: "Interpretación local del pesto, elaborada con identidad tarijeña.",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
    {
      id: "roland-organic-hearts-of-palm-14-46-oz",
      brand: "roland-foods",
      name: "Organic Hearts of Palm",
      category: "Vegetales",
      size: "14.46 oz",
      cities: [],
      image: "assets/products/roland-foods/organic-hearts-of-palm.png",
      featureText: "Palmitos orgánicos de textura firme, listos para ensaladas y preparaciones vegetales.",
      barcode: "041224458147",
      caseQuantity: "12",
      active: true,
    },
    {
      id: "roland-sambal-oelek-8-oz",
      brand: "roland-foods",
      name: "Sambal Oelek Chili Sauce",
      category: "Salsas y condimentos",
      size: "8 oz",
      cities: [],
      image: "assets/products/roland-foods/sambal-oelek.png",
      featureText: "Pasta de chile intensa y equilibrada para sopas, aderezos, arroces y salteados.",
      barcode: "041224873704",
      caseQuantity: "12",
      active: true,
    },
    {
      id: "roland-sardines-olive-oil-4-4-oz",
      brand: "roland-foods",
      name: "Sardines in Olive Oil",
      category: "Conservas de pescado",
      size: "4.4 oz",
      cities: [],
      image: "assets/products/roland-foods/sardines-olive-oil.png",
      featureText: "Sardinas firmes conservadas en aceite de oliva, listas para servir o integrar en recetas.",
      barcode: "041224121225",
      caseQuantity: "10",
      active: true,
    },
    {
      id: "roland-medium-artichoke-hearts",
      brand: "roland-foods",
      name: "Medium Artichoke Hearts",
      category: "Vegetales",
      size: "Presentación internacional",
      cities: [],
      image: "assets/products/roland-foods/artichoke-hearts.png",
      barcode: null,
      caseQuantity: null,
      active: true,
    },
  ],
};
